### ISSUE TITLE
Помилка запуску docker-compose

### ISSUE THREAD

**Issue by das13** [aleks-vorgen/docker-compose#8]
Під час запуску docker-compose up отримуємо помилку запуску:
```
ERROR [2/2] COPY target/*.war shop-server.war
------
 > [2/2] COPY target/*.war shop-server.war:
------
lstat /var/lib/docker/tmp/buildkit-mount755520439/target: no such file or directory
ERROR: Service 'shop-service' failed to build : Build failed
```
Аналогічно для ExchangeRate
Вирішити проблему можна створивши скрипт космпіляції/запуску (див. #7)

**Comment by aleks-vorgen** [comment]
Склонував проект на іншому ПК, навіть без скрипта все піднялось.
Що до #7 додав скрипт
